In [1]:
import tensorflow as tf

In [3]:
# tensorflow dataset is an object type
# feed dataset to model training
# batch and shuffle 
# without taking too much space

In [2]:
import pandas as pd
import numpy as np

# IN MEMORY

In [8]:
inputs = [0,1,2,3]
labels = [1,0,1,0]

In [9]:
dataset = tf.data.Dataset.from_tensor_slices((inputs,labels))

In [10]:
for item in dataset:
    print(item)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [14]:
inputs = np.asarray(inputs)
labels = np.asarray(labels)

In [16]:
dataset = tf.data.Dataset.from_tensor_slices((inputs,labels))
for item in dataset:
    print(item)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=3>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)


In [17]:
df = pd.DataFrame(
{
    "inputs": [0,1,2,3],
    'labels':[1,0,1,0]
})

In [18]:
df

inputs  labels
0       0       1
1       1       0
2       2       1
3       3       0

In [19]:
df.inputs.values

array([0, 1, 2, 3])

In [20]:
dataset = tf.data.Dataset.from_tensor_slices((df['inputs'].values,df['labels'].values))

In [22]:
for item in dataset:
    print(item)

(<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(), dtype=int64, numpy=3>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)


# READ DATA FROM FILE

In [26]:
"""
dataset = tf.data.experimental.make_csv_dataset(
    "train.csv",
    # READING DATA INTO OUR MODEL 16 ROWS AT A TIME
    batch_size=16,
    field_delim=',',
    select_columns= ['PassengerID','Survived','Pclass'],
    # TARGET OR OUTPUT COLUMN - Must also be in out 'select-columns'
    label_name ='Survived'
)
""";


In [4]:
dataset = tf.data.experimental.make_csv_dataset(
    "train.csv",
    batch_size=16,
    field_delim=',',
    select_columns= ['PassengerId','Survived','Pclass'],
    label_name ='Survived'
)

In [5]:
# .take method will take data for total number of batched
for item in dataset.take(3):
    print(item)

(OrderedDict([('PassengerId', <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([509,  33, 541, 613, 268, 580, 420,  39, 126, 606, 728, 115, 131,
       680, 704, 344], dtype=int32)>), ('Pclass', <tf.Tensor: shape=(16,), dtype=int32, numpy=array([3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 2], dtype=int32)>)]), <tf.Tensor: shape=(16,), dtype=int32, numpy=array([0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0], dtype=int32)>)
(OrderedDict([('PassengerId', <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([ 26,  59, 618, 477, 144, 151, 345, 413, 824,   9, 162, 153, 295,
       409, 221, 286], dtype=int32)>), ('Pclass', <tf.Tensor: shape=(16,), dtype=int32, numpy=array([3, 2, 3, 2, 3, 2, 2, 1, 3, 3, 2, 3, 3, 3, 3, 3], dtype=int32)>)]), <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0], dtype=int32)>)
(OrderedDict([('PassengerId', <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([833, 640, 694, 513, 754, 225,  19, 419, 520, 881, 101, 186

# IF WE ARE NOT READING FROM THE FILE 

In [7]:
data = pd.read_csv('train.csv')

In [8]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [9]:
dataset = tf.data.Dataset.from_tensor_slices((data[['Pclass','Age','Parch']].values,data['Survived'].values))

In [10]:
# NOW IT IS NOT SHUFFLED OR BATCHED
for item in dataset.take(1):
    print(item)

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3., 22.,  0.])>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)


In [11]:
# TO MAKE IT SHUFFLED AND BATCHED
# if the data is very unrepresented >> increased the number in .shuffle(###)
dataset = dataset.shuffle(10000).batch(16,drop_remainder=True)