In [1]:
import numpy as np

In [2]:
list_a = [1,2,3,4,5]

In [3]:
np.array(list_a)

array([1, 2, 3, 4, 5])

# arange

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,3)

array([0, 3, 6, 9])

# module zero, one

In [6]:
size=(7,3)

In [7]:
matrix = np.ones(size)

In [8]:
matrix = np.zeros(size)

In [9]:
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# random

In [10]:
np.random.randint(low=0,high=100,size=size)

array([[72, 39, 25],
       [85,  3, 28],
       [10, 89, 56],
       [43,  3, 63],
       [36, 18, 91],
       [56, 49,  2],
       [77, 97,  2]])

# linear space

In [11]:
# y = mx + b
x = 0
y = 10
nb_val = 8
matrix = np.linspace(x,y,nb_val)
print(matrix)

[ 0.          1.42857143  2.85714286  4.28571429  5.71428571  7.14285714
  8.57142857 10.        ]


In [12]:
np.linspace(start=30,stop=76,num=100)

array([30.        , 30.46464646, 30.92929293, 31.39393939, 31.85858586,
       32.32323232, 32.78787879, 33.25252525, 33.71717172, 34.18181818,
       34.64646465, 35.11111111, 35.57575758, 36.04040404, 36.50505051,
       36.96969697, 37.43434343, 37.8989899 , 38.36363636, 38.82828283,
       39.29292929, 39.75757576, 40.22222222, 40.68686869, 41.15151515,
       41.61616162, 42.08080808, 42.54545455, 43.01010101, 43.47474747,
       43.93939394, 44.4040404 , 44.86868687, 45.33333333, 45.7979798 ,
       46.26262626, 46.72727273, 47.19191919, 47.65656566, 48.12121212,
       48.58585859, 49.05050505, 49.51515152, 49.97979798, 50.44444444,
       50.90909091, 51.37373737, 51.83838384, 52.3030303 , 52.76767677,
       53.23232323, 53.6969697 , 54.16161616, 54.62626263, 55.09090909,
       55.55555556, 56.02020202, 56.48484848, 56.94949495, 57.41414141,
       57.87878788, 58.34343434, 58.80808081, 59.27272727, 59.73737374,
       60.2020202 , 60.66666667, 61.13131313, 61.5959596 , 62.06

# regression

In [13]:
# randomize array
arr = np.random.randint(low=0,high=100,size=80)

In [14]:
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.std())
print(arr.var())
print(arr.std()**2)

97
0
46.2875
27.42772035277449
752.2798437499999
752.2798437499999


# 2d and 3d array

In [15]:
arr = np.random.randint(low=0,high=200,size=24)
print(arr)

[ 61 175 127 145 109  77   6  50 108 192  23 179   6  61 112 152  78  41
 134 197 108   2  87  88]


In [16]:
matrix = arr.reshape(8,3)
print(matrix)

[[ 61 175 127]
 [145 109  77]
 [  6  50 108]
 [192  23 179]
 [  6  61 112]
 [152  78  41]
 [134 197 108]
 [  2  87  88]]


# locate

In [17]:
# 3rd row and 3rd column
matrix[2,2]

108

# filtering

In [18]:
matrix[matrix>100]

array([175, 127, 145, 109, 108, 192, 179, 112, 152, 134, 197, 108])

# seed

In [19]:
# Fix randomization for A compilation
np.random.seed(707)
random_matrix = np.random.randint(low=0,high=100,size=10)
random_matrix

array([91, 31, 99, 44, 39, 77, 58, 45, 10, 74])

In [20]:
random_matrix = np.random.randint(low=0,high=100,size=10)
random_matrix

array([67,  2, 86, 91, 90, 74, 73, 20, 45, 28])

In [21]:
np.random.seed(707)
random_matrix = np.random.randint(low=0,high=100,size=10)
random_matrix

array([91, 31, 99, 44, 39, 77, 58, 45, 10, 74])

In [22]:
# 3d with 2 arrays 5R X 1C
random_matrix.reshape(2,5,1)

array([[[91],
        [31],
        [99],
        [44],
        [39]],

       [[77],
        [58],
        [45],
        [10],
        [74]]])